# Site settings 配置站点
title: "virusefender's blog"
description: ' 学而不思则罔，思而不学则殆'
keyword: 'virusdefender,blog'
url: 'https://virusdefender.net' # your host
baseurl: '/'

# Navigation links
nav:
  home: '/'
  tags: '/tags'

# Author 配置博主信息
author: 'virusdefender'
nickname: 'virusefender'
bio: 'biu biu biu'
avatar: 'assets/img/profile.png'

# Search
search: true

# Comments
disqus: false

# Share
social-share: false
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagrame, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/virusdefender'
  github: '//github.com/virusdefender'

# Tags 设置标签
recommend-tags: false # whether or not display recommend-tags on the sidebar
recommend-condition-size: 4 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 2
paginate_path: 'index.php/page/:num/'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

permalink: /index.php/archives/:id/
permalink_custom_vars: ['id']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  extensions:
    - autolink

RSS: true

# Plugins
gems: [jekyll-paginate]
